services:
  db:
    image: postgres:18
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: development
    volumes:
      - pg_volume:/var/lib/postgresql:rw
      - ./postgres/init-scripts:/docker-entrypoint-initdb.d:ro

volumes:
  pg_volume:
    driver: local
